[package]
name = "plonk_circuits"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
algebra = { path = "../../../zexe/algebra/", features = [ "asm", "parallel", "bn_382", "tweedle" ] }
ff-fft = { path = "../../../zexe/ff-fft" }
oracle = { path = "../../oracle" }
rand_core = { version = "0.5" }
array-init = { version = "0.1.1" }
blake2 = "0.7"
