[package]
name = "dlog"
version = "0.1.0"
edition = "2018"

[dev-dependencies]
rand_core = { version = "0.5" }
colored = "1.9.2"
rand = { version = "0.8.0", features = ["getrandom"] }
sprs = "0.7.1"
rayon = { version = "1" }
array-init = "1.0.0"
ark-ff = { version = "0.3.0", features = [ "parallel", "asm" ] }
ark-poly = { version = "0.3.0", features = [ "parallel" ] }

commitment_dlog = { path = "commitment" }
groupmap = { path = "../groupmap" }
mina-curves = { path = "../curves" }
o1-utils = { path = "../utils" }
oracle = { path = "../oracle" }
plonk_protocol_dlog = { path = "plonk" }
plonk_circuits = { path = "../circuits/plonk" }
plonk_15_wires_circuits = { path = "../circuits/plonk-15-wires" }
plonk_15_wires_protocol_dlog = { path = "plonk-15-wires" }
