[workspace]
members = [
    "circuits/plonk",
    "circuits/plonk-15-wires",
    "curves",
    "dlog",
    "dlog/commitment",
    "dlog/plonk",
    "dlog/plonk-15-wires",
    "dlog/plonk-15-wires-plookup",
    "groupmap",
    "oracle",
    "utils",
]

[profile.release]
lto = true
panic = 'abort'
codegen-units = 1
