[workspace]
members = [
    "circuits/plonk",
    "circuits/plonk-15-wires",
    "curves",
    "dlog",
    "dlog/commitment",
    "dlog/plonk",
    "dlog/plonk-15-wires",
    "groupmap",
    "ocaml-gen",
    "ocaml-gen/derive",
    "oracle",
    "utils",
]
exclude = [ "ocaml-gen/tests" ]

[profile.release]
lto = true
panic = 'abort'
codegen-units = 1
