[workspace]
members = [
    "circuits/plonk",
    "circuits/plonk-5-wires",
    "circuits/plonk-5-wires-plookup",
    "circuits/plonk-15-wires",
    "curves",
    "dlog",
    "dlog/commitment",
    "dlog/plonk",
    "dlog/plonk-5-wires",
    "dlog/plonk-5-wires-plookup",
    "dlog/plonk-15-wires",
    "dlog/plonk-15-wires-plookup",
    "groupmap",
    "oracle"
]
exclude = [ "./zexe" ]

[profile.release]
lto = true
panic = 'abort'
codegen-units = 1
