[workspace]
members = [
    "circuits/marlin",
    "circuits/plonk",
    "circuits/plonk-5-wires",
    "dlog",
    "dlog/commitment",
    "dlog/marlin",
    "dlog/plonk",
    "dlog/plonk-5-wires",
    "dlog_solver",
    "groupmap",
    "oracle",
    "pairing",
    "pairing/commitment",
    "pairing/marlin",
    "pairing/plonk",
]
exclude = [ "./zexe" ]

[profile.release]
lto = true
panic = 'abort'
codegen-units = 1
