[workspace]
members = [
    "circuits/marlin",
    "circuits/plonk",
    "circuits/plonk-5-wires",
    "curves",
    "dlog",
    "dlog/commitment",
    "dlog/marlin",
    "dlog/plonk",
    "dlog/plonk-5-wires",
    "dlog_solver",
    "oracle"
]
exclude = [ "./zexe" ]

[profile.release]
lto = true
panic = 'abort'
codegen-units = 1
