[package]
name = "marlin_circuits"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
algebra = { path = "../../zexe/algebra", features = [ "parallel", "bn_382", "tweedle", "asm" ] }
algebra-core = { path = "../../zexe/algebra-core", features = [ "parallel"] }
ff-fft = { path = "../../zexe/ff-fft" }
wasm-bindgen = "0.2.69"
