[package]
name = "marlin_circuits"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
algebra = { git = "https://github.com/o1-labs/zexe/", features = [ "asm", "parallel", "bn_382", "tweedle" ] }
ff-fft = { git = "https://github.com/o1-labs/zexe/" }
