[package]
name = "ocaml-gen"
version = "0.1.0"
edition = "2018"

[dependencies]
ocaml-derive = { path = "./derive" }
ocaml = { version = "0.22.1" }
syn = "1.0.76"
const-random = "0.1.13"
convert_case = "0.4.0"
