[package]
name = "mina-curves"
version = "0.1.0"
edition = "2018"

[dependencies]
ark-ff = { version = "^0.2.0", default-features = false }
ark-ec = { version = "^0.2.0", default-features = false }
ark-r1cs-std = { version = "^0.2.0", default-features = false, optional = true }
ark-std = { version = "^0.2.0", default-features = false }

[dev-dependencies]
ark-relations = { version = "^0.2.0", default-features = false }
ark-serialize = { version = "^0.2.0", default-features = false }
ark-algebra-test-templates = { version = "^0.2.0", default-features = false }

[features]
default = []