[package]
name = "oracle"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
ark-ff = { version = "0.3.0", features = [ "parallel", "asm" ] }
ark-ec = { version = "0.3.0", features = [ "parallel" ] }
ark-poly = { version = "0.3.0", features = [ "parallel" ] }
mina-curves = { path = "../curves" }
ocaml = { version = "0.22.0", optional = true }
rand = "0.8.0"
rayon = { version = "1" }

# for export_test_vectors
num-bigint = { version = "0.4.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
hex = { version = "0.4" }
ark-serialize = "0.3.0"

[dev-dependencies]
hex = { version = "0.4" }

[features]
ocaml_types = [ "ocaml" ]

# for test vectors
default = ["3w"]
3w = [ ]
5w = [ ]
3 = [ ]

[[bin]]
name = "export_test_vectors"
test = false
bench = false
path = "tests/export_test_vectors/export_test_vectors.rs"
