[package]
name = "oracle"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
algebra = { path = "../zexe/algebra", features = [ "parallel", "asm" ] }
mina-curves = { path = "../curves" }
ff-fft = { path = "../zexe/ff-fft", features = [ "parallel"] }
ocaml = { version = "0.22.0", optional = true }
rand = "0.7.3"
rayon = { version = "1" }

[features]

ocaml_types = [ "ocaml" ]
