[package]
name = "oracle"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
algebra = { path = "../zexe/algebra", features = [ "parallel", "bn_382", "tweedle", "asm" ] }
ff-fft = { path = "../zexe/ff-fft" }
rand = "0.7.3"
wasm-bindgen = "0.2.69"
