[package]
name = "oracle"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
algebra = { path = "../zexe/algebra", features = [ "parallel", "asm" ] }
mina-curves = { path = "../curves" }
ff-fft = { path = "../zexe/ff-fft", features = [ "parallel"] }
ocaml = { version = "0.22.0", optional = true }
rand = "0.7.3"
rayon = { version = "1" }

# for test vectors
num-bigint = "0.3"
custom_derive = "0.1.7"
enum_derive = "0.1.7"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
hex = "0.4"

[features]
ocaml_types = [ "ocaml" ]

# for test vectors
default = ["fp_3"]
three_wire = []
five_wire = []
fp_3 = []

[[bin]]
name = "export_test_vectors"
test = false
bench = false
path = "tests/export_test_vectors/main.rs"
