version: 2.1

jobs:
    run-tests:
        docker:
            - image: rust:1.44.1-buster
        steps:
            - checkout
            - run: cargo test

workflows:
    version: 2
    marlin_parallel:
        jobs:
        - run-tests
