[package]
name = "commitment_dlog"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
algebra = { path = "../../zexe/algebra", features = [ "parallel", "bn_382", "tweedle", "asm" ] }
dlog_solver = { path = "../../dlog_solver" }
groupmap = { path = "../../zexe/groupmap" }
ff-fft = { path = "../../zexe/ff-fft", features = [ "parallel" ] }
oracle = { path = "../../oracle" }
rand_core = { version = "0.5" }
colored = "2.0.0"
rand = "0.7.3"
blake2 = "0.7"
itertools = "0.10.0"
array-init = "1.0.0"
wasm-bindgen = "0.2.69"

#[dev-dependencies]
wasm-bindgen-test = "0.3.19"
