[package]
name = "commitment_dlog"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
algebra = { path = "../../../zexe/algebra", branch = "dlog-only-clean-cargo", features = [ "asm", "parallel", "bn_382", "tweedle" ] }
groupmap = { path = "../../../zexe/groupmap", branch = "dlog-only-clean-cargo" }
ff-fft = { path = "../../../zexe/ff-fft", branch = "dlog-only-clean-cargo" }
dlog_solver = { path = "../../dlog_solver", branch = "dlog_solver" }
oracle = { path = "../../oracle" }
rand_core = { version = "0.5" }
colored = "1.9.2"
rand = "0.7.3"
rayon = { version = "1" }
blake2 = "0.7"
itertools = "0.8.2"
