[package]
name = "pairing"
version = "0.1.0"
edition = "2018"

[dependencies]
algebra = { path = "../../zexe/algebra", branch = "dlog-only-clean-cargo", features = [ "asm", "parallel", "bn_382", "tweedle" ] }
ff-fft = { path = "../../zexe/ff-fft", branch = "dlog-only-clean-cargo" }
commitment_pairing = { path = "commitment" }
circuits_pairing = { path = "circuits" }
protocol_pairing = { path = "protocol" }
oracle = { path = "../oracle" }
rand_core = { version = "0.5" }
colored = "1.9.2"
rand = "0.7.3"
sprs = "0.7.1"
