[package]
name = "plonk_protocol_dlog"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
algebra = { path = "../../../zexe/algebra", features = [ "parallel", "bn_382", "tweedle", "asm" ] }
ff-fft = { path = "../../../zexe/ff-fft" }
commitment_dlog = { path = "../commitment" }
plonk_circuits = { path = "../../circuits/plonk" }
oracle = { path = "../../oracle" }
rand_core = { version = "0.5" }
colored = "2.0.0"
rand = "0.7.3"
sprs = "0.9.2"
rayon = "1.5.0"
array-init = "1.0.0"
