[package]
name = "plonk_5_wires_plookup_circuits"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
ark-ff = { version = "0.3.0", features = [ "parallel", "asm" ] }
ark-poly = { version = "0.3.0", features = [ "parallel" ] }
ocaml = { version = "0.18.1", optional = true }
oracle = { path = "../../oracle" }
array-init = { version = "1.0.0" }
blake2 = "0.7"
num-derive = "0.3"
num-traits = "0.2"
rand = "0.8.0"

[features]

ocaml_types = [ "ocaml", "oracle/ocaml_types" ]
