name: Basic rust CI stuff

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  run_checks:
    runs-on: ubuntu-latest
    name: Run some basic checks
    steps:

      - name: Checkout PR
        uses: actions/checkout@v2

      - name: Set up cargo/rust
        run: |
          rustup component add rustfmt 

      - name: build
        run: |
          cargo build

      - name: build ocaml types
        run: |
          cargo build --features ocaml_type
